### ISSUE TITLE
missing Mavlink.cs

### ISSUE THREAD

**Issue by thanhly06** [ArduPilot/MissionPlanner#1232]
anybody can give me file Mavlink.cs
I can't build MP without this file
thanks for watching

**Comment by meee1** [comment]
please install python on your machine. the file is generated during build.

**Comment by magicrub** [comment]
Michael, perhaps we need a more useful error message. This particular
"problem" comes up often.

**Comment by meee1** [comment]
Agreed, I might switch back to manually build as needed, and include the file in commits.
the reasons for this are
1. prevent this issue
2. there is no requirement to rebuild from the same xml's on every build
3. because of the change every build, all dependancys on this dll also get rebuilt.
4. ability to track change to the autogenerated file.

so in effect this will decrease compile time.

**Comment by magicrub** [comment]
And there I go trying to be helpful and just end up causing a huge pain. Sorry!
