### ISSUE TITLE
Support sending SET_GPS_GLOBAL_ORIGIN message for Copter and Rover (at least)

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#1702]
In Copter-3.5.4 and Rover-3.2-rc3 (and higher) if the user wishes to use non-GPS navigation (i.e. the Pozyx system, visual odometry, etc) then the EKF must be told where the EKF origin should be placed using the SET_GPS_GLOBAL_ORIGIN message (http://mavlink.org/messages/common#SET_GPS_GLOBAL_ORIGIN).  We should add a new option to the right-mouse-button menu called "Set EKF Origin Here".  This will be a very rarely used message but I don't think we should hide it on the Ctrl-F menu.

By the way, in older versions of the vehicle firmware we used the SET_HOME_POSITION message (http://mavlink.org/messages/common#SET_HOME_POSITION) to set the EKF origin but this led to some issues with callers accidentally setting the EKF origin when they really only wanted to set home.

We need this message for both Copter and Rover.

**Comment by meee1** [comment]
I assume this message is guarded on copter/rover side to prevent crashing?

**Comment by meee1** [comment]
currently MP implemented no safeguards around this. I could check for if armed?

**Comment by rmackay9** [comment]
Thanks!

@meee1, I don't think it should be necessary to check anything on the MP side.  In ardupilot we check the message to make sure it's a valid lat/lon/alt.  Also we only accept setting the origin once and most users will want to set it before arming.

**Comment by NotShittyProgrammer** [comment]
@meee1 @rmackay9 are there any workarounds in ArduPlane to "Set EKF Origin Here" in order to manually set a new EKF origin during flight without GPS, in case of accumulated drift and known position from the ground? As far as I know, currently we can only set the EKF origin once before rebooting the flight controller. Is there a way to do this using LUA scripts without modifying the ArduPilot firmware itself? I understand all the potential risks of using this functionality in such a way, but it is crucial for my concept. I’d really appreciate any advice or suggestions

**Comment by rmackay9** [comment]
Hi @NotShittyProgrammer,

Instead of setting the EKF origin (which should never move) the MAV_CMD_EXTERNAL_POSITION_ESTIMATE can be used to reset the estimated location when the vehicle is deadreckoning.  I've created a [wiki issue here](https://github.com/ArduPilot/ardupilot_wiki/issues/6761) to add some documentation but perhaps you can figure out how to use it even before we get that documentation completed.
