### ISSUE TITLE
Resending request for parameters when parameters already arriving?

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MissionPlanner#2025]
I'm not sure of the cause of this issue, it may or may not be an MP issue but when testing the ArduPilot Rover with a TX2 companion computer running APSync and ROS the MP takes a very very long time to load all the Parameters.  The time required is variable - sometimes 5min sometimes over an hour.

During this long wait, the parameter loading update screen is displayed and it is constantly displaying, "Already Got param xxxxx".  It's a guess but I suspect that MP is constantly requesting the parameters be sent even though they are already arriving.  I don't really understand the specifics of how parameters are loaded but perhaps @peterbarker can also assist with some info.

I think this problem only started happening after I updated to the latest beta this morning.  Note that I'm running master Rover.

![mp-already-loaded-params](https://user-images.githubusercontent.com/1498098/49491848-2210a100-f899-11e8-931e-2c150d61d12e.png)

**Comment by meee1** [comment]
this is because of packet loss. I don't believe this is a MP issue
MP request the full list... it gets say  60% of the params so MP will request the full list again, as pulling 10 at a time is very time consuming. during this seconds request mp shows already got.

if in the first pull over 75% of the params are got, mp will pull params 10 at a time. untill its complete. this process is slower.

**Comment by Naterater** [comment]
If it says "Already Got" but it doesn't truly have it, then why display "Already Got"? Otherwise there needs to be some improvement here. Parameters are now taking minutes to load, and usually it's all wasted time at the field. Around my part of the world, "Got" is a very informal word that is only spoken. When it's written, we usually use other words such as received or found for clarity.

Hopefully this is all solved when the new parameter transfer protocol comes.

**Comment by proficnc** [comment]
The most common cause I have seen of this issue, is having something spamming the mavlink during startup.  This used to happen heaps with the old code on a solo due to the gimbal, I have also seen it when going via a companion computer etc.

As far as the language... PR is welcome to translate it from perfect Australian to whatever better version of English you so desire :)

**Comment by rmackay9** [comment]
@meee1,

OK, I'll try adding more debug and see if that helps clear up what's going on.  But I suspect that MP shouldn't keep requesting the full list over and over and over if the parameters are already arriving.  I think if they're already arriving it should wait until they arrive before asking for all to be sent again.  Anyway, I will gather more evidence... maybe I'm wrong.

**Comment by meee1** [comment]
@rmackay9  it is not, there is a  4 second gap, that is used to control this.
if you can provide the tlog of the connect it should all be in there

**Comment by meee1** [comment]
from what I can tell with the info I have at the moment

you connected
mp requested the full param list
mp got less than 75% of the params back
mp waits 4 seconds from the last valid paramter packet
mp requested the full list again because its got less than 75%
mp may or maynot have gotten the missing 25+%, and displayed already got for the params it had already seen.
if you now had above 75%, mp will start pulling the missing params 10 at a time. until it has them all.

**Comment by Naterater** [comment]
It seems to me like that's a lot of wasted effort to receive all of the parameters multiple times when the success rate is below 75%. Is there no reliable way to make this parameter more efficient without a complete re-work of the system?

**Comment by rmackay9** [comment]
I'm going to close this because I think we need more investigation..
