### ISSUE TITLE
m8n 

### ISSUE THREAD

**Issue by manotroll** [ArduPilot/MissionPlanner#2051]
#### Issue details
_Please describe the problem, or desired feature_
px4 does not detect m8n
but connected directly to the serial I have response
$GNRMC,,V,,,,,,,,,,N*4D
$GNVTG,,,,,,,,,N*2E
$GNGGA,,,,,,0,00,99.99,,,,,,*56
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E
$GPGSV,1,1,00*79
$GLGSV,1,1,00*65
$GNGLL,,,,,,V,N*7A
$GNRMC,,V,,,,,,,,,,N*4D
$GNVTG,,,,,,,,,N*2E
$GNGGA,,,,,,0,00,99.99,,,,,,*56
$GNGSA,A,1,,,,,,,,,,,,,99.99,99.99,99.99*2E

#### Version
_What version was the issue encountered with_
1.3.62
#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
_What type of airframe (flying wing, glider, hex, Y6, octa etc)_
quad
#### Hardware type
_What autopilot hardware was used? (pixhawk, pixracer, PX4FMU etc)_
pixhawk
#### Logs
_Please provide a link to any relevant logs that show the issue_

**Comment by rmackay9** [comment]
This should really be raised in the copter so I'll close this.

The issue appears to be that the UBlox GPS is outputting a NMEA string instead of a UBlox binary.  It would be best to reconfigure the GPS to output the UBLox binary protocol because it provides more information that the EKF can use (3D velocities I think).. failing that it's possible to use a NMEA GPS but the GPS_TYPE must be explicitely set to "NMEA".
