### ISSUE TITLE
Signing issue when compiling mission planner

### ISSUE THREAD

**Issue by galdalali** [ArduPilot/MissionPlanner#2191]
#### Issue details
I'm trying to compile mission planner and got the following errors in updater project:
`The command ""C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe" sign /n "Michael Oborne" /t http://timestamp.verisign.com/scripts/timestamp.dll "C:\Users\Gal\Documents\bit\MissionPlanner\Updater\bin\Debug\Updater.exe"" exited with code 1.`
and
`No certificates were found that met all the given criteria.
`
The "Sign the ClickOnce Manifests" checkbox is unchecked.
How can I solve this issue?

Thanks, Gal
		

#### Version
1.3.68

**Comment by meee1** [comment]
remove the post build command.
I will not be distributing the cert used to sign the updater

**Comment by GBJin** [comment]
I remove all the post build command but still got the certificates errors.
![111](https://user-images.githubusercontent.com/38447788/62844489-507e3000-bcf4-11e9-814d-f61ec6d9f8d4.PNG)
I also got other errors below:
![222](https://user-images.githubusercontent.com/38447788/62844500-668bf080-bcf4-11e9-923b-608b21a2f21a.PNG)
I installed the latest MP version 1.3.68
![333](https://user-images.githubusercontent.com/38447788/62844538-9affac80-bcf4-11e9-814b-931f87744758.PNG)
The main code is downloaded from the website, which should be the latest.
Do anyone have the issues? I used to compile MP 1.3.56, but last week I downloaded for the latest code and try to compile, it come up with these errors. Most likely due to the Xamarin project, but I can't solve it.

**Comment by meee1** [comment]
remove the post build commands in the updater project

**Comment by GBJin** [comment]
Thanks, certificate errors solved.
But I still have errors like below:
![111](https://user-images.githubusercontent.com/38447788/62855421-c69a8b00-bd24-11e9-8f0b-9fe14ca1d2f5.PNG)
Cannot resolve Assembly or Windows Metadata file 'C:\MissionPlanner-master (1)\MissionPlanner-master\ExtLibs\Xamarin\Xamarin\bin\Release\netstandard2.0\Xamarin.dll'	
I tried to find Xamarin.dll, but there's not such dll file in either installed MP folder or the main code folder download from Github. What did I miss?
I installed .NET Core SDK 2.2.108. And pretty much checked every items which need to be checked.
![222](https://user-images.githubusercontent.com/38447788/62855638-5d674780-bd25-11e9-888e-794e224b9f08.PNG)

**Comment by meee1** [comment]
install the mobile components

**Comment by GBJin** [comment]
Problem solved, Thanks for the reply!

**Comment by ojas032** [comment]
> remove the post build commands in the updater project

I could not find Updater project
