### ISSUE TITLE
Lidar ST VL53L1X Holybro is not working during Automission plan

### ISSUE THREAD

**Issue by edpamilar** [ArduPilot/MissionPlanner#3369]
#### Issue details
I am using Lidar ST VL53L1X from holybro with ardupilot firmware; this lidar is set facing down detecting altitude. 
When using it with automission plan mode, lidar is not working, i mean it doesnt react when detecting low ground level.(mission plan is at 4m altitude in all waypoints but 1 waypoint got much higher ground level in which the drone should automatically up to maintain the 4m altitude). Please help on how to fix this.
Also please let me know what is the best rangefinder with ardupilot firmware in auto mission mode.

#### Platform
[  ] Copter

#### Airframe type
_Quadcopter

#### Hardware type
_Pixhawk Px6c

#### Mission planner version
1.3.81 build 1.3.8741.25556

Ardupilot firmware 
V4.5.2

**Comment by rmackay9** [comment]
Hi @edpamilar,

Thanks for the report.  Could you create a new topic in the Copter-4.5 support forum and please include an onboard log as well if possible. https://discuss.ardupilot.org/c/arducopter/copter-45/174

I'll close this issue here because support issues should first be raised in the forums and this is most likely a flight code issue, not a Mission Planner issue.
