### ISSUE TITLE
NAMED_VALUE_FLOAT revert back to "customfieldx" once Mission Planner restarts

### ISSUE THREAD

**Issue by flyrobot27** [ArduPilot/MissionPlanner#3379]
#### Issue details
When Mission Planner restarts, all the custom fields sent via NAMED_VALUE_FLOAT (Which starts with MAV_) revert back to "customfield", instead of sticking to the MAV_ name

![image](https://github.com/user-attachments/assets/c206224f-a790-4801-967d-4d12b872ecc2)

Even once the drone is connected, the name does not revert back to MAV_:
![image](https://github.com/user-attachments/assets/1b0eec0f-ab74-40b5-9972-27e838019443)

#### Version
Mission Planner 1.3.81 build 1.3.8741.25556 ArduCopter V4.5.3 (ee14ff38)

#### Platform
[  ] All
[  ] AntennaTracker
[X] Copter
[  ] Plane
[  ] Rover
[  ] Sub

#### Airframe type
N/A

#### Hardware type
Matek H743-WLITE with Raspberry pi 5
Telemetry radio is Holybro SiK Telemetry Radio V3 (915 mhz 500 mv)

#### Logs
I'm not sure what log I can provide but let me know

**Comment by EosBandi** [comment]
This is the normal modus operandi since you don't know what names will come from the flight controller at startup.
If you want permanent naming then you have to define the names in the config.xml
<customfield1>MAV_name1</customfield1>
<customfield2>MAV_name2</customfield2>

This is slightly inconvenient, but it allows the system to be dynamic.

**Comment by EosBandi** [comment]
See mu updated comment above...

**Comment by flyrobot27** [comment]
I can see that, thank you

**Comment by flyrobot27** [comment]
I also personally found a workaround. Just click to a different panel and click back (I clicked "Config") and it seems the parameter names have refreshed
