### ISSUE TITLE
error when building mp1.3.80 based on Visual Studio community 2022

### ISSUE THREAD

**Issue by channgan** [ArduPilot/MissionPlanner#3434]
#### Issue details
![6c9b6a11b92829beb78c2a91b09df4b](https://github.com/user-attachments/assets/5d0046c3-b116-46c8-8164-4888a0762b8d)
![108893a2f4aa43af2d7778bccfee4c0](https://github.com/user-attachments/assets/00a3f83e-caa0-46d7-81e8-ad17518dc37c)

#### Version
1.3.80

**Comment by Godeffroy** [comment]
Did you buid the Extlibs before ? Because you need to build it (at least once) before building mission planner

This one for you : 
![image](https://github.com/user-attachments/assets/8cba7b67-3390-48b1-8d01-eb967868417c)

or better the wohle folder 
![image](https://github.com/user-attachments/assets/a27e8820-9b69-48e8-9139-19fdaca6e93a)

**Comment by channgan** [comment]
thanks，i copy my friend’s code，maybe the way i use git is wrong
