### ISSUE TITLE
firmware options missing under Mono in 1.3.7

### ISSUE THREAD

**Issue by foobarbecue** [ArduPilot/MissionPlanner#558]
The "Beta firmware" "Download firmwares," "load custom firmware," and "pick previous firmware" options which are present when you run Mission Planner on Windows are missing when it is run on Ubuntu 14.04.

![missingfwopts](https://cloud.githubusercontent.com/assets/854789/3845967/e41a84d0-1e57-11e4-8b10-d58b1d83f657.png)

**Comment by tjones99** [comment]
OK, took me a while to figure this out because I wasn't seeing and Advanced View option on my Config/Tuning screen... its actually the Layout option.. Basic or Advanced.... If it is set to Basic when you go to the Firmware screen in Initial Setup the Custom and Beta Firmware options show up briefly while the page refreshes the current versions then they disappear. When you select Layout>>Advanced then they stay.
