### ISSUE TITLE
Safety improvements for  Actions window on Flight data screen

### ISSUE THREAD

**Issue by nicksargeant** [ArduPilot/MissionPlanner#691]
While it appears that there are some confirmation boxed for critical actions e.g:
![image](https://cloud.githubusercontent.com/assets/5547169/4766604/fb6309fe-5b52-11e4-91b2-5b25f65c4825.png)
I believe that there is not sufficient protection for all items selectable on this screen.
In additional to "Do Action" I believe that at the very least, Arm/Disarm and Restart Mission should have a confirmation. I can appreciate the need for immediacy when disarming but when out in the field, with screen glare and using a trackpad, it is almost too easy for a operator to inadvertently click the wrong button (fortunately I have not done this yet but I see it happening).   

Additionally, would it be possible to select what flight modes were accessible with the drop down menu (perhaps via an editable .xml file) or atleast have a confirmation of mode change? 
At the moment it is too easy for a user to change into ACRO mode when perhaps then intended to go to AUTO mode. 
Thank you!

**Comment by edwinhayes** [comment]
@meee1 Sorry, this an old ticket, but probably better than creating a new one.  Can you explain why you deliberately didn't want to add a confirmation prior to arming the aircraft?

**Comment by meee1** [comment]
@edwinhayes my aim is to not be intrusive. what is you use case/process flow that makes you think it would be needed?

**Comment by edwinhayes** [comment]
@meee1 We just had an incident where an aircraft was unintentionally armed on the ground, because an engineer went to click on some other button on the actions pane, but accidentally hit the adjacent arm button instead.

Other actions which could be considered 'dangerous' (such as disarming) do have a confirmation dialogue, so why not arming?  The fact that disarming does require a confirmation actually makes the situation worse, since the behaviour is asymmetrical; having accidentally clicked on 'arm', you can't undo the mistake by immediately clicking 'disarm'.
